stages:
  - build
  - lint

build:
  stage: build
  image: golang:1.20-alpine
  tags:
    - go
  before_script:
    - apk add --no-cache git 
    - apk add --no-cache make 
  script:
    - make build

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  tags:
    - go
  script:
    - golangci-lint run
